<?php

namespace AdminBundle\Repository;

/**
 * dsfdsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class dsfdsRepository extends \Doctrine\ORM\EntityRepository
{
}
