<?php

namespace AdminBundle\Repository;

/**
 * ProductInterfaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductInterfaceRepository extends \Doctrine\ORM\EntityRepository
{
}
