<?php

namespace AdminBundle\Repository;

/**
 * Product_typeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
