<?php

namespace AdminBundle\Repository;

/**
 * ProductInterfaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastFive(){
        $qb = $this->createQueryBuilder('product')
            ->orderBy('product.id', 'DESC')
            ->setMaxResults(5);
        return $qb->getQuery()->getResult();

    }

}
